SELECT 
    TO_CHAR(
        o.ORIG_ORDER_DT_TM AT TIME ZONE 'Australia/Melbourne', 
        'YYYY-MM-DD HH24:MI:SS'
    ) AS ORIG_ORDER_DT_TM_MELBOURNE,
    o.ORDER_MNEMONIC,
    o.ORDER_ID
FROM WESTERNHEALTH_P2031.ORDERS o
WHERE CAST(o.ORIG_ORDER_DT_TM AT TIME ZONE 'Australia/Melbourne' AS TIMESTAMP) 
          >= TO_TIMESTAMP('2026-04-01 12:43:00', 'YYYY-MM-DD HH24:MI:SS')
  AND CAST(o.ORIG_ORDER_DT_TM AT TIME ZONE 'Australia/Melbourne' AS TIMESTAMP) 
          <= TO_TIMESTAMP('2026-04-01 12:45:00', 'YYYY-MM-DD HH24:MI:SS')
  AND o.ORDER_ID = 5268999757.00;   -- keep for testing