SELECT 
    TO_CHAR(
        o.UPDT_DT_TM AT TIME ZONE 'Australia/Melbourne', 
        'YYYY-MM-DD HH24:MI:SS'
    ) AS UPDT_DT_TM_MELBOURNE,
    o.ORDER_MNEMONIC,
    o.ORDER_ID
FROM WESTERNHEALTH_P2031.ORDERS o
WHERE o.UPDT_DT_TM >= SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '5' MINUTE;