SELECT 
    COUNT(*)
FROM WESTERNHEALTH_P2031.ORDERS o
WHERE CAST(o.ORIG_ORDER_DT_TM AT TIME ZONE 'Australia/Melbourne' AS TIMESTAMP) 
          >= TO_TIMESTAMP('2026-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
  AND CAST(o.ORIG_ORDER_DT_TM AT TIME ZONE 'Australia/Melbourne' AS TIMESTAMP) 
          < TO_TIMESTAMP('2026-04-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
;