SELECT DISTINCT
      P_A.ALIAS AS PATIENT_URN
    , P.NAME_FULL_FORMATTED AS PATIENT
    , TO_CHAR(P.BIRTH_DT_TM, 'DD-MON-YYYY') AS PATIENT_DOB
    , CV_SEX.DISPLAY AS PATIENT_SEX
    , CASE 
        WHEN ELH.LOC_FACILITY_CD > 0 THEN CV_FAC_ELH.DISPLAY 
        ELSE CV_FAC_E.DISPLAY 
      END AS FACILITY
    , CASE 
        WHEN ELH.LOC_NURSE_UNIT_CD > 0 THEN CV_NURSE_ELH.DISPLAY 
        ELSE CV_NURSE_E.DISPLAY 
      END AS NURSE_UNIT
    , E_A.ALIAS AS ENCOUNTER_FIN
    , CV_EVENT.DISPLAY AS ADMINISTERED
    , CVO.ALIAS AS AIR_ALIAS
    , CV_ENTRY_MODE.DISPLAY AS ENTRY_MODE
    , C_M_R.SUBSTANCE_LOT_NUMBER AS BATCH_LOT_NUMBER
    , TO_CHAR(
        C_M_R.SUBSTANCE_EXP_DT_TM AT TIME ZONE 'Australia/Melbourne', 
        'YYYY-MM-DD HH24:MI:SS'
    ) AS EXPIRY_DATE
    , CV_MANUF.DISPLAY AS MANUFACTURER
    , TO_CHAR(
        C_E.PERFORMED_DT_TM AT TIME ZONE 'Australia/Melbourne', 
        'YYYY-MM-DD HH24:MI:SS'
    ) AS COMPLETED
    , E_A.ALIAS AS ENCOUNTER_NO
    , CV_ROUTE.DISPLAY AS ROUTE
    , CV_SITE.DISPLAY AS SITE
    , C_M_R.ADMIN_DOSAGE AS DOSAGE
    , CV_DOSAGE_UNIT.DISPLAY AS DOSAGE_UNIT

FROM WESTERNHEALTH_P2031.CLINICAL_EVENT C_E

JOIN WESTERNHEALTH_P2031.ENCOUNTER E 
    ON E.ENCNTR_ID = C_E.ENCNTR_ID
    AND E.LOC_FACILITY_CD != 4038465.00 /* NOT "DEMO 1 HOSPITAL" */

JOIN WESTERNHEALTH_P2031.ENCNTR_ALIAS E_A 
    ON E_A.ENCNTR_ID = C_E.ENCNTR_ID
    AND E_A.ENCNTR_ALIAS_TYPE_CD = 1077 /* 'FIN NBR' FROM CODE SET 319 */
    AND E_A.ACTIVE_IND = 1 /* ACTIVE FIN NBRS ONLY */
    AND E_A.END_EFFECTIVE_DT_TM > SYSDATE /* EFFECTIVE FIN NBRS ONLY */

LEFT JOIN WESTERNHEALTH_P2031.ENCNTR_LOC_HIST ELH 
    ON ELH.ENCNTR_ID = C_E.ENCNTR_ID
    AND ELH.ACTIVE_IND = 1 
    AND ELH.BEG_EFFECTIVE_DT_TM < C_E.PERFORMED_DT_TM 
    AND ELH.END_EFFECTIVE_DT_TM > C_E.PERFORMED_DT_TM

JOIN WESTERNHEALTH_P2031.PERSON P 
    ON P.PERSON_ID = C_E.PERSON_ID
    AND P.NAME_LAST_KEY NOT LIKE '%TESTWHS%'

JOIN WESTERNHEALTH_P2031.PERSON_ALIAS P_A 
    ON P_A.PERSON_ID = E.PERSON_ID
    AND P_A.ALIAS_POOL_CD = 9569589.00 /* FILTERS FOR UR NUMBER ALIAS' ONLY */
    AND P_A.END_EFFECTIVE_DT_TM > SYSDATE
    AND P_A.ACTIVE_IND = 1

LEFT JOIN WESTERNHEALTH_P2031.CE_MED_RESULT C_M_R 
    ON C_M_R.EVENT_ID = C_E.EVENT_ID

LEFT JOIN WESTERNHEALTH_P2031.ORDER_CATALOG_SYNONYM OCS 
    ON OCS.SYNONYM_ID = C_M_R.SYNONYM_ID

LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV 
    ON UPPER(CV.DEFINITION) = UPPER(OCS.MNEMONIC)
    AND CV.CODE_SET = 104551 /* "AIR VACCINE CODES" */

LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE_OUTBOUND CVO 
    ON CVO.CODE_VALUE = CV.CODE_VALUE
    AND CVO.CODE_SET = 104551 /* "AIR VACCINE CODES" */

/* Lookups for UAR_GET_CODE_DISPLAY */
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_SEX ON CV_SEX.CODE_VALUE = P.SEX_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_FAC_ELH ON CV_FAC_ELH.CODE_VALUE = ELH.LOC_FACILITY_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_FAC_E ON CV_FAC_E.CODE_VALUE = E.LOC_FACILITY_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_NURSE_ELH ON CV_NURSE_ELH.CODE_VALUE = ELH.LOC_NURSE_UNIT_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_NURSE_E ON CV_NURSE_E.CODE_VALUE = E.LOC_NURSE_UNIT_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_EVENT ON CV_EVENT.CODE_VALUE = C_E.EVENT_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_ENTRY_MODE ON CV_ENTRY_MODE.CODE_VALUE = C_E.ENTRY_MODE_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_MANUF ON CV_MANUF.CODE_VALUE = C_M_R.SUBSTANCE_MANUFACTURER_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_ROUTE ON CV_ROUTE.CODE_VALUE = C_M_R.ADMIN_ROUTE_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_SITE ON CV_SITE.CODE_VALUE = C_M_R.ADMIN_SITE_CD
LEFT JOIN WESTERNHEALTH_P2031.CODE_VALUE CV_DOSAGE_UNIT ON CV_DOSAGE_UNIT.CODE_VALUE = C_M_R.DOSAGE_UNIT_CD

WHERE 
    C_E.EVENT_CLASS_CD = 228 /* "IMMUNIZATION" FILTER */
    AND C_E.VIEW_LEVEL = 1 /* VIEWABLE (NOT REVERTED ETC) */
    AND C_E.AUTHENTIC_FLAG = 1 /* DETERMINES WHETHER THE EVENT RECORD HAS BEEN AUTHENTICATED (REMOVES DUPLICATES) AND 'PATIENT REFUSED ROWS*/
    AND C_E.RESULT_STATUS_CD = 25.00 /* "AUTH (VERIFIED)" RESULT STATUS, THIS EFFECTIVELY REMOVES DUPLICTES*/
    
    /* TIME FILTERS - Last 2 months of administrations */
    AND CAST(C_E.PERFORMED_DT_TM AT TIME ZONE 'Australia/Melbourne' AS TIMESTAMP) 
        >= ADD_MONTHS(CAST(SYSTIMESTAMP AT TIME ZONE 'Australia/Melbourne' AS TIMESTAMP), -2)
;